### ISSUE TITLE
New Data source - South Korea

### ISSUE THREAD

**Issue by charian** [openaq/openaq-fetch#555] opened 2018-11-18 14:10 UTC
https://www.data.go.kr/dataset/15000581/openapi.do?lang=en
http://openapi.airkorea.or.kr/

[airkorea_openapi_guide-v1_6_1.docx](https://github.com/openaq/openaq-fetch/files/2592824/airkorea_openapi_guide-v1_6_1.docx)

**Comment by mondorescue** [comment] 2019-03-07 16:29
More info in issue #362

**Comment by jflasher** [comment] 2019-03-09 19:34
Thanks @charian! Closing this as a duplicate of #362 and we can keep the conversation going there.

**Closed by jflasher** 2019-03-09 19:34 UTC
